### ISSUE TITLE
Possibility to return score/distance

### ISSUE THREAD

**Issue by moooji** [neondatabase/pg_embedding#40]
Hi! Thank you for this great extension. We are wondering if there is a way to return the score (distance) of each result item similar to how pgvector is doing?

**Comment by JAAvander** [comment]
For anyone here confused about how to get the similarity scores of queried rows, 
expressions like this: `embedding <-> ARRAY[3,3,3]` evaluate to the score.  
In many examples expressions like this are used in order by, but one can also just select it, and order by it later:
```sql
SELECT id, (embedding <-> ARRAY[3,3,3]) AS score FROM documents ORDER BY score; 
```
